before_build:
  - nuget restore
  - nuget install xunit.runners -ExcludeVersion

test_script:
  - xunit.runners\tools\xunit.console.clr4.x86 "C:\projects\appveyorunittest\ClassLibrary1\bin\Debug\ClassLibrary1.dll"
